# spring configuration
spring:
  application:
    name: ajax-practices-backend

  devtools:
    restart:
      enabled: true # 코드 수정 시 애플리케이션 자동 재시작
    livereload:
      enabled: true # 브라우저에 LiveReload 서버를 열어서, HTML/CSS/JS 수정 시 자동 새로고침 지원

  mvc:
    static-path-pattern: /assets/** # /assets일 경우에만 정적 리소스 찾기
  web:
    resources:
      static-locations: [classpath:/assets/, file:/ajax-practices-uploads/]
  servlet:
    multipart:
      enabled: true
      max-file-size: 10485760
      max-request-size: 104857600
      file-size-threshold: 5242880

# server configuration
server:
  port: 8080
  servlet:
    context-path: /
  error:
    whitelabel:
      enabled: false # 기본 제공되는 Whitelabel Error Page 비활성화
    path: /error